### ISSUE TITLE
Issue #1

### ISSUE THREAD

**Issue by rictic** [rictic/test-repo-1#1]
body text

**Comment by usergenic** [comment]
i have something to say here in this comment about this issue.

**Comment by keanulee** [comment]
+1 seeing the same thing

**Comment by aomarks** [comment]
I think we're over thinking this issue.

**Comment by justinfagnani** [comment]
Hi @rictic!

Issue #3 is great, btw. I hope it's still great in the future.

**Comment by bicknellr** [comment]
But how does this interact with #2?

**Comment by rictic** [comment]
Issue migrated to rictic/test-repo-2#1

**Comment by rictic** [comment]
Issue migrated to rictic/test-repo-2#2

**Comment by rictic** [comment]
Issue migrated to rictic/test-repo-2#3

**Comment by rictic** [comment]
Issue migrated to rictic/test-repo-2#4
